import type { MeshData } from './types';

/** Size in bytes of the binary STL header. */
export const STL_HEADER_BYTES = 80;

/** Bytes per triangle record in a binary STL: normal + 3 vertices + attribute count. */
export const STL_TRIANGLE_BYTES = 12 * 4 + 2;

/**
 * Serialize a triangle mesh as a binary STL file. Normals are computed per
 * triangle from the vertex winding; the attribute byte count is zero.
 */
export function meshToBinaryStl(mesh: MeshData): ArrayBuffer {
  const { vertices, indices } = mesh;
  const triangleCount = indices.length / 3;
  if (!Number.isInteger(triangleCount)) {
    throw new Error(`Index count ${indices.length} is not a multiple of 3`);
  }
  const buffer = new ArrayBuffer(STL_HEADER_BYTES + 4 + triangleCount * STL_TRIANGLE_BYTES);
  const view = new DataView(buffer);
  const headerText = 'Gridfinity bin generated by GridfinityGenerator';
  for (let i = 0; i < Math.min(headerText.length, STL_HEADER_BYTES); i++) {
    view.setUint8(i, headerText.charCodeAt(i));
  }
  view.setUint32(STL_HEADER_BYTES, triangleCount, true);

  let offset = STL_HEADER_BYTES + 4;
  for (let t = 0; t < triangleCount; t++) {
    const i0 = indices[t * 3] * 3;
    const i1 = indices[t * 3 + 1] * 3;
    const i2 = indices[t * 3 + 2] * 3;
    const ax = vertices[i0], ay = vertices[i0 + 1], az = vertices[i0 + 2];
    const bx = vertices[i1], by = vertices[i1 + 1], bz = vertices[i1 + 2];
    const cx = vertices[i2], cy = vertices[i2 + 1], cz = vertices[i2 + 2];
    // Normal = normalized cross product of the two edge vectors.
    const ux = bx - ax, uy = by - ay, uz = bz - az;
    const vx = cx - ax, vy = cy - ay, vz = cz - az;
    let nx = uy * vz - uz * vy;
    let ny = uz * vx - ux * vz;
    let nz = ux * vy - uy * vx;
    const len = Math.hypot(nx, ny, nz);
    if (len > 0) {
      nx /= len;
      ny /= len;
      nz /= len;
    }
    const values = [nx, ny, nz, ax, ay, az, bx, by, bz, cx, cy, cz];
    for (const value of values) {
      view.setFloat32(offset, value, true);
      offset += 4;
    }
    view.setUint16(offset, 0, true);
    offset += 2;
  }
  return buffer;
}

/** Serialize a mesh as a binary STL Blob ready for download. */
export function meshToStlBlob(mesh: MeshData): Blob {
  return new Blob([meshToBinaryStl(mesh)], { type: 'model/stl' });
}
