import type { Manifold, ManifoldToplevel, SimplePolygon } from 'manifold-3d';
import type { Font } from 'opentype.js';
import {
  binInteriorSizeMm,
  binOuterSizeMm,
  HEIGHT_UNIT,
  OUTER_CORNER_RADIUS,
  WALL_THICKNESS,
} from '../gridfinity/constants';
import { roundedRectPolygon } from '../gridfinity/binGenerator';
import type { BinParams } from '../gridfinity/types';
import { extrudeLabel } from './extrude';
import {
  boldenText,
  buildShelfStructure,
  LABEL_MARGIN,
  layoutLabelFace,
  SHELF_DEPTH_MARGIN,
  specHasLabel,
} from './placement';
import type { LabelSpec } from './placement';

/**
 * Swappable label inserts and the bin slot that holds them. The geometry is
 * dimensioned to interchange with the Printables model "Gridfinity bin with
 * printable label by Pred" (printables.com/model/592545): all figures below
 * were measured from that model's published meshes (label 3MF/STEP files and
 * the 1x1x6 bin), so an insert printed from here fits a Pred bin and a Pred
 * insert fits a bin from here. The insert drops into a shallow channel above
 * the label shelf and lies between the front wall, an end stop at the back,
 * and a side cheek at each end; the front-wall overhang keeps its front edge
 * from bowing up.
 */

/** Thickness of the label insert plate. */
export const INSERT_THICKNESS = 0.8;

/** Depth (front to back) of the label insert plate. */
export const INSERT_DEPTH = 11.5;

/** Corner radius of the label insert plate. */
export const INSERT_CORNER_RADIUS = 0.4;

/**
 * How much shorter the insert is than the bin's outer width (1.85 mm per
 * side): a one-cell insert is 37.8 mm long on the 41.5 mm bin.
 */
export const INSERT_END_INSET = 3.7;

/** Depth (front to back) of the insert channel; 0.5 mm clearance over the insert. */
export const SLOT_DEPTH = 12.0;

/** Height of the insert channel; 0.2 mm clearance over the insert thickness. */
export const SLOT_HEIGHT = 1.0;

/** Total side clearance of the channel over the insert length. */
export const SLOT_SIDE_CLEARANCE = 0.5;

/**
 * The end stop along the channel's back edge: a ridge rising from the
 * channel floor to the nominal bin top that keeps the insert from sliding
 * into the bin interior. The insert drops into the channel from above and
 * lies between this stop, the front wall, and the side cheeks; the front
 * overhang (below) keeps its front edge from bowing up.
 */
export const RETAINER_BASE_DEPTH = 0.9;

/**
 * The overhang above the channel along the front wall (depth and height of a
 * 45-degree strip) that holds the insert's front edge down. In the reference
 * model this overhang is part of its thicker wall; here it is added as a
 * strip welded onto the wall, only on bins with a stacking lip (a flat-topped
 * bin keeps its flat top; the retaining lip and side cheeks still hold the
 * insert).
 */
export const FRONT_OVERHANG = 0.7;

/**
 * How deep the label face is inlaid into the insert's top, and how far the
 * inlay solid reaches below its pocket floor so the two solids are welded.
 */
export const INSERT_INLAY_DEPTH = 0.4;
export const INSERT_INLAY_WELD = 0.05;

/** Length of the label insert for a bin spanning `cells` grid cells. */
export function insertLengthMm(cells: number): number {
  return binOuterSizeMm(cells) - INSERT_END_INSET;
}

/** Width of the insert channel for a bin spanning `cells` grid cells. */
export function slotChannelWidthMm(cells: number): number {
  return insertLengthMm(cells) + SLOT_SIDE_CLEARANCE;
}

/**
 * Where an insert generated by buildInsertSolids (resting on z = 0, centred
 * on the origin) sits inside the bin's slot: centred in the channel, resting
 * on the channel floor.
 */
export function insertPositionInBin(params: BinParams): {
  x: number;
  y: number;
  z: number;
} {
  const outerDepth = binOuterSizeMm(params.gridY);
  const bodyTop = params.heightUnits * HEIGHT_UNIT;
  return {
    x: 0,
    y: -outerDepth / 2 + WALL_THICKNESS + SLOT_DEPTH / 2,
    z: bodyTop - SLOT_HEIGHT,
  };
}

/** Extrude a (y, z) profile along X over the given width, starting at x = 0. */
function prismFromProfile(
  m: ManifoldToplevel,
  profile: SimplePolygon,
  width: number,
): Manifold {
  const section = new m.CrossSection([profile], 'NonZero');
  try {
    return section.extrude(width).rotate(90, 0, 90);
  } finally {
    section.delete();
  }
}

/**
 * The slot shelf: the shared plate-and-ribs shelf structure with its top face
 * one channel height below the nominal bin top (forming the channel floor,
 * extended under the retaining lip), plus the retaining lip along the
 * channel's back edge, a side cheek at each channel end that centres the
 * insert, and (on bins with a stacking lip) the front-wall overhang strip.
 * Unioned with the bin body like the embossed label shelf; the channel itself
 * is simply the open space above the plate.
 */
export function buildSlotShelf(m: ManifoldToplevel, params: BinParams): Manifold {
  const outerWidth = binOuterSizeMm(params.gridX);
  const outerDepth = binOuterSizeMm(params.gridY);
  const interiorWidth = binInteriorSizeMm(params.gridX);
  const bodyTop = params.heightUnits * HEIGHT_UNIT;
  const floorTop = bodyTop - SLOT_HEIGHT;
  const channelWidth = slotChannelWidthMm(params.gridX);

  const yOuter = -outerDepth / 2;
  const yInner = yOuter + WALL_THICKNESS;
  const yBack = yInner + SLOT_DEPTH;
  const yLipBack = yBack + RETAINER_BASE_DEPTH;

  const parts: Manifold[] = [
    buildShelfStructure(m, params, floorTop, SLOT_DEPTH + RETAINER_BASE_DEPTH),
  ];

  // End stop along the channel's back edge, spanning the channel width.
  const stopProfile: SimplePolygon = [
    [yBack, floorTop],
    [yLipBack, floorTop],
    [yLipBack, bodyTop],
    [yBack, bodyTop],
  ];
  parts.push(prismFromProfile(m, stopProfile, channelWidth).translate(-channelWidth / 2, 0, 0));

  // Side cheeks between the channel ends and the interior walls, so the
  // insert is centred instead of sliding sideways.
  const cheekWidth = (interiorWidth - channelWidth) / 2;
  if (cheekWidth > 0) {
    for (const side of [-1, 1]) {
      parts.push(
        m.Manifold.cube([cheekWidth, yLipBack - yInner, SLOT_HEIGHT]).translate(
          side === -1 ? -interiorWidth / 2 : channelWidth / 2,
          yInner,
          floorTop,
        ),
      );
    }
  }

  // Front-wall overhang strip above the channel, with a 45-degree top so it
  // prints as a continuation of the wall. Only where wall material continues
  // above the nominal bin top, i.e. on bins with a stacking lip.
  if (params.stackingLip) {
    const overhangProfile: SimplePolygon = [
      [yOuter, bodyTop],
      [yInner + FRONT_OVERHANG, bodyTop],
      [yInner, bodyTop + FRONT_OVERHANG],
      [yOuter, bodyTop + FRONT_OVERHANG],
    ];
    parts.push(
      prismFromProfile(m, overhangProfile, channelWidth).translate(-channelWidth / 2, 0, 0),
    );
  }

  const prism = m.Manifold.union(parts);
  for (const part of parts) part.delete();

  // Clip to the bin's rounded outer outline, like the embossed label shelf.
  const outline = m.Manifold.extrude(
    [roundedRectPolygon(outerWidth, outerDepth, OUTER_CORNER_RADIUS)],
    bodyTop + FRONT_OVERHANG,
  );
  const shelf = m.Manifold.intersection(prism, outline);
  prism.delete();
  outline.delete();
  if (shelf.status() !== 'NoError') {
    throw new Error(`Slot shelf construction produced an invalid solid: ${shelf.status()}`);
  }
  return shelf;
}

/**
 * Cutter clearing the insert channel's open space, for builders that first
 * fill the bin interior solid (the pocket bin): subtracting this and then
 * unioning buildSlotShelf restores the channel. Slightly oversized in height
 * so no film is left over the channel.
 */
export function slotClearanceCutter(m: ManifoldToplevel, params: BinParams): Manifold {
  const outerDepth = binOuterSizeMm(params.gridY);
  const bodyTop = params.heightUnits * HEIGHT_UNIT;
  const channelWidth = slotChannelWidthMm(params.gridX);
  const yInner = -outerDepth / 2 + WALL_THICKNESS;
  const eps = 0.01;
  return m.Manifold.cube([channelWidth, SLOT_DEPTH, SLOT_HEIGHT + eps]).translate(
    -channelWidth / 2,
    yInner,
    bodyTop - SLOT_HEIGHT,
  );
}

/** The two parts of a label insert, kept separate for per-part coloring. */
export interface InsertSolids {
  /** The insert plate with the label face pocketed out of its top. */
  body: Manifold;
  /** The label face inlay, flush with the plate top, or null for a blank insert. */
  label: Manifold | null;
}

/**
 * Build a label insert: a flat plate (resting on z = 0, centred on the
 * origin, ready to print) with the label face inlaid flush into its top as a
 * separate solid, so the face prints in a second filament. An empty spec
 * yields a blank insert with a null label. The caller owns both manifolds.
 */
export function buildInsertSolids(
  m: ManifoldToplevel,
  font: Font,
  spec: LabelSpec,
  cells: number,
): InsertSolids {
  const length = insertLengthMm(cells);
  const eps = 0.01;
  let body = m.Manifold.extrude(
    [roundedRectPolygon(length, INSERT_DEPTH, INSERT_CORNER_RADIUS)],
    INSERT_THICKNESS,
  );
  if (!specHasLabel(spec)) {
    if (body.status() !== 'NoError') {
      throw new Error(`Insert generation produced an invalid solid: ${body.status()}`);
    }
    return { body, label: null };
  }

  const parts = layoutLabelFace(
    font,
    spec,
    length - 2 * LABEL_MARGIN,
    INSERT_DEPTH - 2 * SHELF_DEPTH_MARGIN,
  ).map((part) => boldenText(m, part));
  const pocketTop = INSERT_THICKNESS - INSERT_INLAY_DEPTH;

  const faceSolids = parts.map((part) =>
    extrudeLabel(m, part.polygons, INSERT_INLAY_DEPTH + INSERT_INLAY_WELD + eps, part.fillRule),
  );
  const face = faceSolids.length === 1 ? faceSolids[0] : m.Manifold.union(faceSolids);
  if (faceSolids.length > 1) {
    for (const solid of faceSolids) solid.delete();
  }

  // Pocket the plate from the top down to the inlay depth, and let the inlay
  // reach INSERT_INLAY_WELD below the pocket floor so the union of the two
  // parts is one welded solid with a flush top.
  const pocketCutter = face.translate(0, 0, pocketTop);
  const pocketed = m.Manifold.difference(body, pocketCutter);
  body.delete();
  pocketCutter.delete();
  body = pocketed;
  const label = face
    .translate(0, 0, pocketTop - INSERT_INLAY_WELD)
    .trimByPlane([0, 0, -1], -INSERT_THICKNESS);
  face.delete();
  if (body.status() !== 'NoError' || label.status() !== 'NoError') {
    const status = body.status() !== 'NoError' ? body.status() : label.status();
    body.delete();
    label.delete();
    throw new Error(`Insert generation produced an invalid solid: ${status}`);
  }
  return { body, label };
}
